### ISSUE TITLE
Breadcrumbs unusable on Safari

### ISSUE THREAD

**Issue by shkn-not-strrd** [Availity/gatsby-theme-availity#20]
The header collides with the navigation breadcrumbs, making them unusable, and unsightly.....but only on Safari. (Firefox and Chrome are OK.) Tested Safari version is 12.1.2.

<img width="1037" alt="Screen Shot 2019-10-01 at 1 48 18 PM" src="https://user-images.githubusercontent.com/4172421/65987671-4951e380-e454-11e9-9643-26bd8a2ccdf4.png">

Unsure if Safari support is within scope, but wanted to document the behavior in case it is.

**Comment by GoPro16** [comment]
We should be supporting all browsers with the theme. IE works fine for me so looks like only a bug with Safari from what I can see

**Comment by gregmartDOTin** [comment]
Hey, I submitted a PR for this #24
